import Header from './Header';
import Footer from './Footer';
import Nav from './Nav';
import Home from '../../webpages/Home';
import About from '../../webpages/About';
import Contact from '../../webpages/Contact';
import Cat from '../../webpages/Cat';
import Details from '../../webpages/Details';
import Cart from '../../webpages/Cart';
import Checkout from '../../webpages/Checkout';
import Preview from '../../webpages/Preview';
import PaystackResponse from '../../webpages/PaystackResponse';
import BankDeposit from '../../webpages/BankDeposit';
import PaymentOptions from '../../webpages/PaymentOptions';
import SizeGuide from '../../webpages/SizeGuide';
import Delivery from '../../webpages/Delivery';
import ExchangeAndReturns from '../../webpages/ExchangeAndReturns';
import Register from '../../webpages/Register';
import Login from '../../webpages/Login';
import Logout from '../../webpages/Logout';
import ForgotPassword from '../../webpages/ForgotPassword';
import Missing from '../../webpages/Missing';

export {Header, Footer, Nav, Home, About, Contact, Cat, Details, Cart, Checkout, Preview, PaystackResponse, BankDeposit, PaymentOptions, SizeGuide, Delivery, ExchangeAndReturns, Register, Login, Logout, ForgotPassword, Missing};